version: 2

references:
  docker_hub_authentication: &docker_hub_authentication
    auth:
      username: tky007
      password: docdocuu009

jobs:
  # buildジョブ: CircleCI上でDockerコンテナを作成してテストする
  build:
    # docker-composeがインストール済みの仮想マシンをプル
    machine:
      image: circleci/classic:edge
      <<: *docker_hub_authentication

    steps:
      # CI環境上のworking_directoryの値の場所にGitリポジトリをコピー
      - checkout
      - run:
          name: Dockerコンテナの起動
          command: docker-compose up --build -d
      - run:
          name: db接続を待機
          command: sleep 10
      - run:
          name: テストを実行
          command: docker-compose exec php phpunit
      - run:
          name: Dockerコンテナの停止
          command: docker-compose down

  # deployジョブ: EC2にSSH接続して、デプロイを実行する
  deploy:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      # CircleCI に登録した秘密鍵を呼び出す
      - add_ssh_keys:
      # CircleCI に登録した環境変数を使って SSH
      - run:
          name: EC2、bastion経由でwebサーバーにSSH接続し、最新コードをpull
          command: |
            ssh -p 49222 ${USER_NAME}@${HOST_NAME}
            ssh -p 49222 -i “id_rsa” yakukai@172.16.3.11
            cd /var/www/html/yakukai/
            git pull

workflows:
  version: 2
  # build_and_deploy ジョブ: 一番最初に呼ばれるジョブ
  build_and_deploy:
    # build ジョブと deploy ジョブを呼び出す
    jobs:
      - build
      - deploy:
          # deployより先にbuildさせる
          requires:
            - build
          # masterブランチにpushされた場合のみdeployを実行する
          filters:
            branches:
              only: main
